# Generated by Django 4.2.7 on 2023-11-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AskLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail", models.EmailField(max_length=254, verbose_name="Почта")),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
            ],
        ),
    ]
