# Generated by Django 4.2.7 on 2023-11-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="askletter",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
        migrations.RenameField(
            model_name="askletter",
            old_name="text",
            new_name="message",
        ),
        migrations.AddField(
            model_name="askletter",
            name="name",
            field=models.CharField(default=0, max_length=250, verbose_name="Имя"),
            preserve_default=False,
        ),
    ]
