# Generated by Django 4.2.7 on 2023-11-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_askletter_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="askletter",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Прочитано"),
        ),
    ]
