# Generated by Django 4.2.7 on 2023-11-22 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_askletter_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="askletter",
            options={
                "ordering": ["-is_read"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
