# Generated by Django 4.2.7 on 2023-11-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Доступность"),
        ),
    ]
